pipeline {
    agent { 
        // dockerfile true 
        docker {  image 'yfy668/serverless:v1.0.2' }
        }

    stages {
        stage('Serverless Plugin'){
            steps{  
                dir('./serverless_code'){
                      sh 'sls plugin install -n serverless-python-requirements'
                      sh 'npm i -D serverless-dotenv-plugin '
                      sh 'npm install --save-dev serverless-iam-roles-per-function'
                      // sh 'pip3 install awscli --upgrade'  
            }
                                  }  
        }      
                  
        //  stage('create S3 bucket and upload files') {
        //     steps{
        //         withAWS(credentials: '461f9b14-52bf-4989-8852-9e0988783409', region:'ap-southeast-2'){ 
        //         // sh 'aws s3api create-bucket --bucket=jr-de-project-prod1 --region=ap-southeast-2 --create-bucket-configuration LocationConstraint=ap-southeast-2'
        //         sh 'aws s3api create-bucket --bucket=imba-prod1 --region=ap-southeast-2 --create-bucket-configuration LocationConstraint=ap-southeast-2'
        //         sh 'aws s3 cp ./serverless_code/files/glue_job.py s3://imba-prod1/scripts/glue_job.py'
        //         sh 'aws s3 cp ./serverless_code/files/confluent.zip s3://imba-prod1/confluent/confluent.zip'
        //         }
        //           }
        // }         

        stage('serverless deploy') {
            steps{
                dir('./serverless_code'){
                     withAWS(credentials: '461f9b14-52bf-4989-8852-9e0988783409', region:'ap-southeast-2'){
                        sh 'sls deploy -v'
                    }
                }
            }
        }

        // stage('serverless remove') {
        //     steps{
        //         dir('./serverless_code'){
        //            withAWS(credentials: '461f9b14-52bf-4989-8852-9e0988783409', region:'ap-southeast-2'){
        //         sh 'sls remove'
        //           }
        //         }
        //     }
        // }
        
    //     stage('Terraform Init') {    //         steps{
    //             sh 'terraform init'
    //               }
    //     }
    //     stage('Terraform plan') {
    //         steps{
    //             withAWS(credentials: '8058ad1c-fdf5-4ae4-b62d-a0127bcd6006', region:'ap-southeast-2'){  
    //                 sh 'terraform plan -out=tfplan -input=false'
    //         }
    //     }
    // }
    //     stage('Terraform apply'){
    //         steps{
    //             withAWS(credentials: '8058ad1c-fdf5-4ae4-b62d-a0127bcd6006', region:'ap-southeast-2'){
    //                 sh "terraform apply -input=false tfplan"
    //             }
    //         }            
    //     }
    }
}